version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo "Entered the pre-build phase"
      - $(aws ecr get-login  --no-include-email --region us-east-2)
  build:
    commands:
      - echo "Entered build phase"
      - cd book-service
      - mvn compile
      - mvn package
      - echo " building docker image"
      - docker build -t service/booksapp .
      - docker tag service/booksapp 097345079740.dkr.ecr.us-east-2.amazonaws.com/service-registry:booksapp
  post_build:
    commands:
    - echo "Entered the post-build phase"
    - docker push 097345079740.dkr.ecr.us-east-2.amazonaws.com/service-registry:booksapp
    - printf '[{"name":"booksapp-container","imageUri":"%s"}]' 097345079740.dkr.ecr.us-east-2.amazonaws.com/service-registry:booksapp > taskdefinition.json
artifacts:
  files:
    - book-service/taskdefinition.json